services:
  rebot:
    build:
      context: .
      dockerfile: ./dockerfile
    restart: always
    logging:
      driver: local
    env_file:
      - .env
    # environment:
    #   - REBOT_DISCORD_TOKEN=editme
    #   - REBOT_GEMINI_TOKEN=editme
  watchtower_rebot:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP='true'
    restart: always